version: '3.1'
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test-job
    ports:
      - "5439:5432"
  app:
    ports:
      - "8089:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test-job
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - db

